language: c
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-9
      - openmpi-bin
      - python-pip

install:
  - export FC=/usr/bin/gfortran-9
  - gfortran --version
  - pip install --user --upgrade FoBiS.py


script:
  - FoBiS.py build -mode static-gnu

#   - gfortran -fprofile-arcs -ftest-coverage -O0 hello.f90 -o hello
#   - ./hello

after_success:
  - bash <(curl -s https://codecov.io/bash)