language: python

dist: bionic
python:
   - 3.8

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo apt-get -q update
   - sudo apt-get -y install binutils
   - sudo apt-get -y install graphviz
   - sudo apt-get -y install gfortran-7
   - sudo apt-get install libopenmpi-dev openmpi-bin libhdf5-openmpi-dev
   - sudo apt-get -y install python3-pip
   - sudo apt-get -y install python3-setuptools
   - python --version
   - git submodule update --init

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - export FC=/usr/bin/gfortran-7
  - ln -fs /usr/bin/gfortran-7 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-7
  - ln -fs /usr/bin/gcov-7 "$HOME/.local/bin/gcov" && gcov --version
  - sudo -H pip3 install --upgrade pygooglechart
  - sudo -H pip3 install --upgrade graphviz
  - sudo -H pip3 install --upgrade future
  - sudo -H pip3 install --upgrade configparser
  - sudo -H pip3 install --upgrade markdown-checklist 
  - sudo -H pip3 install --upgrade ford
  - sudo -H pip3 install --upgrade FoBiS.py && FoBiS.py --version

script:
  - FoBiS.py rule -ex makecoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)