language: c
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-9
      - open-mpi
      - python-pip


# script:
#   - gfortran -fprofile-arcs -ftest-coverage -O0 hello.f90 -o hello
#   - ./hello

after_success:
  - bash <(curl -s https://codecov.io/bash)