language: c
sudo: false

python:
  - 3.7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-9
      - openmpi-bin
      - python-pip

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - export FC=/usr/bin/gfortran-9
  - ln -fs /usr/bin/gfortran-9 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-9
  - ln -fs /usr/bin/gcov-9 "$HOME/.local/bin/gcov" && gcov --version
  - pip install --user --upgrade FoBiS.py


script:
  - FoBiS.py build -mode static-gnu

#   - gfortran -fprofile-arcs -ftest-coverage -O0 hello.f90 -o hello
#   - ./hello

after_success:
  - bash <(curl -s https://codecov.io/bash)