errored_subroutine – Fortran Logger
errored_subroutine Interface
7 statements
Source File
private interface errored_subroutine
Generic external subroutines that return non-zero error codes
Calls
Called by
Contents
Module Procedures
errored_subroutine_I1P errored_subroutine_I2P errored_subroutine_I4P errored_subroutine_I8P errored_subroutine_LOGICAL
Module Procedures
private subroutine errored_subroutine_I1P(logger, error)
Dummy external subroutine that returns non-zero error code, 1 byte
Arguments
Type Intent Optional Attributes Name
class(fortran_logger_t), intent(inout) :: logger
Fortran logger class
integer(kind=I1P), intent(out) :: error
Error code
private subroutine errored_subroutine_I2P(logger, error)
Dummy external subroutine that returns non-zero error code, 2 bytes
Arguments
Type Intent Optional Attributes Name
class(fortran_logger_t), intent(inout) :: logger
Fortran logger class
integer(kind=I2P), intent(out) :: error
Error code
private subroutine errored_subroutine_I4P(logger, error)
Dummy external subroutine that returns non-zero error code, 4 bytes
Arguments
Type Intent Optional Attributes Name
class(fortran_logger_t), intent(inout) :: logger
Fortran logger class
integer(kind=I4P), intent(out) :: error
Error code
private subroutine errored_subroutine_I8P(logger, error)
Dummy external subroutine that returns non-zero error code, 8 bytes
Arguments
Type Intent Optional Attributes Name
class(fortran_logger_t), intent(inout) :: logger
Fortran logger class
integer(kind=I8P), intent(out) :: error
Error code
private subroutine errored_subroutine_LOGICAL(logger, error)
Dummy external subroutine that returns logical False status
Arguments
Type Intent Optional Attributes Name
class(fortran_logger_t), intent(inout) :: logger
Fortran logger class
logical, intent(out) :: error
Error code
Call graph
errored_subroutine calls errored_subroutine_i4p, errored_subroutine_i1p, errored_subroutine_i2p, errored_subroutine_logical, errored_subroutine_i8p
test_ignore_error_codes calls errored_subroutine
run_tests calls test_ignore_error_codes