run_tests – Fortran Logger
run_tests Program
36 statements
Source File
Uses
iso_fortran_env
fortran_logger
test_check_alloc_m
test_ignore_error_codes_m
test_unit_change_m
test_check_json_m
penf
Program designed to test Fortran Logger
Calls
Contents
Variables
logger rank np null_unit out_unit err_unit
Variables
Type Attributes Name Initial
type(fortran_logger_t) :: logger
Fortran logger class
integer(kind=I4P) :: rank
MPI process number
integer(kind=I4P) :: np
MPI number of processes
integer(kind=I4P) :: null_unit
Unit connected to “/dev/null”
integer(kind=I4P) :: out_unit
Unit used to print info and debug messages: stdout on rank = 0 and null_unit otherwise
integer(kind=I4P) :: err_unit
Unit used to print error and warn messages: stderr on rank = 0 and null_unit otherwise
Call graph
run_tests calls test_ignore_error_codes, test_check_alloc, test_check_json, test_unit_change
test_ignore_error_codes calls str, errored_subroutine
test_unit_change calls str
errored_subroutine calls errored_subroutine_i4p, errored_subroutine_i1p, errored_subroutine_i2p, errored_subroutine_logical, errored_subroutine_i8p