module test_unit_change_m
!< Module to test change_unit method of Fortran Logger
use fortran_logger, only : fortran_logger_t, LOGGER_DEBUG_LEVEL
use penf, only: I4P, str
use iso_fortran_env, only: output_unit
implicit none
private
public :: test_unit_change

contains

  subroutine test_unit_change(logger, rank, np, null_unit)
  !< Tester subroutine
    class(fortran_logger_t),  intent(inout) :: logger     !< Fortran logger class
    integer(I4P),             intent(in)    :: rank       !< MPI rank
    integer(I4P),             intent(in)    :: np         !< MPI size
    integer(I4P),             intent(in)    :: null_unit  !< /dev/null unit
    integer(I4P)                            :: r          !< Counter
    integer(I4P)                            :: out_unit   !< Output unit

    call logger%info('***************************************************************')
    call logger%info('               Testing "change_unit" method                    ')
    call logger%info('***************************************************************')

    do r = 0, np - 1
      out_unit = null_unit; if(rank == r) out_unit = output_unit
      call logger%change_unit(LOGGER_DEBUG_LEVEL, out_unit)
      call logger%debug('This message was generated by rank = '//trim(str(n=rank,no_sign=.true.)), routine = 'test_unit_change')
    enddo
    ! Restore unit
    out_unit = null_unit; if(rank == 0) out_unit = output_unit
    call logger%change_unit(LOGGER_DEBUG_LEVEL, out_unit)

    call logger%info('***************************************************************')
    call logger%info('                  Tests passed...                              ')
    call logger%info('***************************************************************')
  end subroutine test_unit_change
end module test_unit_change_m